kind: Cluster
apiVersion: kind.x.k8s.io/v1alpha4
metadata:
  name: wisecow-cluster
spec:
  controlPlane:
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 4499
        hostPort: 4499
        protocol: TCP
  nodes:
    - role: control-plane
      image: kindest/node:v1.27.3
      extraPortMappings:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
                        
